kind = "api"
previewPath = "/api"
title = "API Server"
version = "1.0.0"
id = "3B4_FFSkEVBkAeYMFRJ2e"

[[services]]
localPort = 8080
name = "API Server"
paths = ["/api"]

[services.development]
run = "python /home/runner/workspace/artifacts/api-server/tg_server.py"

[services.production]

[services.production.build]
args = []

[services.production.run]
args = ["python", "/home/runner/workspace/artifacts/api-server/tg_server.py"]

[services.production.run.env]
PORT = "8080"
NODE_ENV = "production"

[services.production.health.startup]
path = "/api/healthz"
